{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "conditions-number.fullname" . }}
  labels:
    {{- include "conditions-number.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "conditions-number.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Object
      object:
        describedObject:
          kind: Service
          name: "{{ .Values.resolver.name }}"
        metric:
          name: "awk_work_queue_length"
          selector:
            matchLabels:
              name: "{{ .Values.resolver.queue.name }}"
        target:
          type: Value
          value: "{{ .Values.resolver.queue.targetLength }}"
    {{- if .Values.autoscaling.targetCPUUtilizationValue }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: {{ .Values.autoscaling.targetCPUUtilizationValue }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationValue }}
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: {{ .Values.autoscaling.targetMemoryUtilizationValue }}
    {{- end }}
{{- end }}
