apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: "{{ .Values.priority.class }}"
value: {{ .Values.priority.value }}
globalDefault: false
description: "This priority class should be used for critical services only."
preemptionPolicy: "{{ .Values.priority.preemptionPolicy }}"
