name: Staging-ARM

on:
  push:
    branches:
      - "master"

env:
  COMPONENT: conditions-number
  VERSION: latest
  CHART_VERSION: 0.0.0

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Registry login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}

      - name: Staging
        run: make staging-arm

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.12.0

      - name: Helm Lint
        run: |
          helm lint helm/${COMPONENT}

      - name: Helm Package
        run: |
          helm dependency update helm/${COMPONENT}
          mkdir helm/package
          helm package helm/${COMPONENT} --destination helm/package
          cd helm/package
          helm repo index .
          
      - name: Helm Upgrade
        run: |
          helm upgrade --install ${COMPONENT} helm/package/${COMPONENT}-0.0.0.tgz \
            --set-string podAnnotations.commit=$(git rev-parse --short HEAD) \
            --values helm/${COMPONENT}/values-arm.yaml
